apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vizier-suggestion-bayesianoptimization
  namespace: katib
  labels:
    app: vizier
    component: suggestion-bayesianoptimization
spec:
  replicas: 1
  template:
    metadata:
      name: vizier-suggestion-bayesianoptimization
      labels:
        app: vizier
        component: suggestion-bayesianoptimization
    spec:
      containers:
      - name: vizier-suggestion-bayesianoptimization
        image: registry.ingress.ktensorgym.us-east-1.k8s.lyft.net/katib/suggestion-bayesianoptimization:0.0.1
        ports:
        - name: api
          containerPort: 6789