apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vizier-earlystopping-medianstopping
  namespace: katib
  labels:
    app: vizier
    component: earlystopping-medianstopping
spec:
  replicas: 1
  template:
    metadata:
      name: vizier-earlystopping-medianstopping
      labels:
        app: vizier
        component: earlystopping-medianstopping
    spec:
      containers:
      - name: vizier-earlystopping-medianstopping
        image: registry.ingress.ktensorgym.us-east-1.k8s.lyft.net/katib/earlystopping-medianstopping:0.0.1
        ports:
        - name: api
          containerPort: 6789
#        resources:
#          requests:
#            cpu: 500m
#            memory: 500M
#          limits:
#            cpu: 500m
#            memory: 500M
