apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vizier-suggestion-grid
  namespace: katib
  labels:
    app: vizier
    component: suggestion-grid
spec:
  replicas: 1
  template:
    metadata:
      name: vizier-suggestion-grid
      labels:
        app: vizier
        component: suggestion-grid
    spec:
      containers:
      - name: vizier-suggestion-grid
        image: registry.ingress.ktensorgym.us-east-1.k8s.lyft.net/katib/suggestion-grid:0.0.1
        ports:
        - name: api
          containerPort: 6789
#        resources:
#          requests:
#            cpu: 500m
#            memory: 500M
#          limits:
#            cpu: 500m
#            memory: 500M
